package bjo.supermercado.gui;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import bjo.supermercado.model.Detalle;
import bjo.supermercado.model.Factura;
import bjo.supermercado.model.Producto;
import bjo.supermercado.utils.FacturasUtils;
import bjo.supermercado.utils.ProductosAlmacenados;

/**
 *
 * @author argli
 */
public class Principal extends javax.swing.JFrame {

    ProductosAlmacenados productUtils;
    FacturasUtils facturasUtils;
    Map<String, Producto> productos;
    List<Factura> facturas;
    LinkedList<Detalle> detalles = null;
    public static final double IVA = 1.19;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        productUtils = new ProductosAlmacenados();
        productos = productUtils.cargarProductos();

        facturasUtils = new FacturasUtils();
        facturas = facturasUtils.cargarFacturas();
        detalles = new LinkedList<>();
    }

    private void limpiarVenta() {
        lblSubtotal.setText("0.00");
        lblIva.setText("0.00");
        lblTotal.setText("0.00");
        detalles.clear();
        DefaultTableModel dtm = (DefaultTableModel) tblDetalles.getModel();
        dtm.setRowCount(0);
    }

    /**
     * Redondea un número a 2 decimales
     *
     * @param d
     * @return
     */
    private double redondear(double d) {
        return Double.parseDouble(String.format("%.2f", d));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelVenta = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetalles = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblSubtotal = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCarrito = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        menuItemListar = new javax.swing.JMenuItem();
        menuItemAgregar = new javax.swing.JMenuItem();
        menuItemActualizar = new javax.swing.JMenuItem();
        menuItemEliminar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuItemIncrementar = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuItemNuevaVenta = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Mercado");

        panelVenta.setBorder(javax.swing.BorderFactory.createTitledBorder("Venta"));

        tblDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(tblDetalles);

        jLabel1.setText("Subtotal:");

        jLabel2.setText("IVA:");

        jLabel3.setText("Total:");

        lblSubtotal.setText("0.00");

        lblIva.setText("0.00");

        lblTotal.setText("0.00");

        btnCarrito.setText("Agregar Producto");
        btnCarrito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCarritoActionPerformed(evt);
            }
        });

        btnFacturar.setText("Facturar");
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelVentaLayout = new javax.swing.GroupLayout(panelVenta);
        panelVenta.setLayout(panelVentaLayout);
        panelVentaLayout.setHorizontalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelVentaLayout.createSequentialGroup()
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSubtotal)
                            .addComponent(lblTotal)
                            .addComponent(lblIva))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCarrito, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFacturar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelVentaLayout.setVerticalGroup(
            panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSubtotal)
                    .addComponent(btnCarrito))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIva)
                    .addComponent(btnFacturar))
                .addGap(18, 18, 18)
                .addGroup(panelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Acciones");
        jMenu1.setToolTipText("");

        jMenu3.setText("Productos");

        menuItemListar.setText("Listar");
        menuItemListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarProductos(evt);
            }
        });
        jMenu3.add(menuItemListar);

        menuItemAgregar.setText("Agregar");
        menuItemAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProducto(evt);
            }
        });
        jMenu3.add(menuItemAgregar);

        menuItemActualizar.setText("Actualizar");
        menuItemActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarProducto(evt);
            }
        });
        jMenu3.add(menuItemActualizar);

        menuItemEliminar.setText("Eliminar");
        menuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProducto(evt);
            }
        });
        jMenu3.add(menuItemEliminar);
        jMenu3.add(jSeparator1);

        menuItemIncrementar.setText("Incrementar precios 5%");
        menuItemIncrementar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incrementarPrecios(evt);
            }
        });
        jMenu3.add(menuItemIncrementar);

        jMenu1.add(jMenu3);

        jMenu4.setText("Facturas");

        jMenuItem5.setText("Listar");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarFacturas(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenu1.add(jMenu4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ventas");

        menuItemNuevaVenta.setText("Nueva venta");
        menuItemNuevaVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNuevaVentaActionPerformed(evt);
            }
        });
        jMenu2.add(menuItemNuevaVenta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listarProductos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarProductos
        System.out.println("listar productos");
        String[][] data = new String[productos.size()][2];
        int c = -1;
        for (String k : productos.keySet()) {
            c++;
            data[c] = new String[]{productos.get(k).getCodigo(), String.valueOf(productos.get(k).getPrecio())};
        }

        DefaultTableModel dtm = new DefaultTableModel(data, new String[]{"Codigo", "Precio"});

        PanelTabla panel = new PanelTabla();
        panel.setModel(dtm);

        JOptionPane.showMessageDialog(this, panel, "Listar productos", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_listarProductos

    private void agregarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProducto
        PanelProducto p = new PanelProducto();
        if (JOptionPane.showConfirmDialog(this, p, "Agregar nuevo producto", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
            productos.put(p.getCodigo(), new Producto(p.getCodigo(), Double.parseDouble(p.getPrecio())));
            productUtils.actualizarProductos(productos);
            JOptionPane.showMessageDialog(this, "Se agregó el producto", "Nuevo producto", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_agregarProducto

    private void actualizarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarProducto
        String codigo = JOptionPane.showInputDialog(this, "Introduce el codigo del producto", "Actualizar producto", JOptionPane.OK_CANCEL_OPTION);
        if (codigo != null && !codigo.isEmpty()) {
            if (productos.containsKey(codigo)) {
                Producto p = productos.get(codigo);
                PanelProducto panel = new PanelProducto(p.getCodigo(), p.getPrecio().toString());
                if (JOptionPane.showConfirmDialog(this, panel, "Actualizar producto", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                    if (!p.getCodigo().equals(panel.getCodigo())) {
                        productos.remove(p.getCodigo());
                    }
                    productos.put(panel.getCodigo(), new Producto(panel.getCodigo(), Double.parseDouble(panel.getPrecio())));
                    productUtils.actualizarProductos(productos);
                    JOptionPane.showMessageDialog(this, "Se actualizó el producto", "Producto actualizado", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado", "Actualizar producto", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_actualizarProducto

    private void eliminarProducto(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProducto
        String codigo = JOptionPane.showInputDialog(this, "Introduce el codigo del producto", "Eliminar producto", JOptionPane.OK_CANCEL_OPTION);
        if (codigo != null && !codigo.isEmpty()) {
            if (productos.containsKey(codigo)) {
                productos.remove(codigo);
                productUtils.actualizarProductos(productos);
                JOptionPane.showMessageDialog(this, "Se eliminó el producto", "Eliminar producto", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Producto no encontrado", "Elimninar producto", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_eliminarProducto

    private void incrementarPrecios(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incrementarPrecios
        productos.values().forEach(p -> {
            p.setPrecio(redondear(p.getPrecio() * 1.05));
        });
        productUtils.actualizarProductos(productos);
        JOptionPane.showMessageDialog(this, "Se incrementó el precio de los productos en 5%", "Incrementar precios", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_incrementarPrecios

    private void btnCarritoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCarritoActionPerformed
        do {
            PanelDetalleFactura pdf = new PanelDetalleFactura(productos);
            if (JOptionPane.showConfirmDialog(this, pdf, "Agregar a la venta", JOptionPane.OK_CANCEL_OPTION) == JOptionPane.OK_OPTION) {
                Detalle d = pdf.getDetalle();
                if (d != null) {
                    detalles.add(d);
                } else {
                    break;
                }
            } else {
                break;
            }
        } while (true);

        Double subtotal = 0.00;
        Double iva;
        Double total;

        String[] cols = new String[]{"Codigo", "Cantidad", "Precio", "Total"};
        String[][] data = new String[detalles.size()][4];
        for (int i = 0; i < data.length; i++) {
            subtotal += detalles.get(i).getTotal();
            data[i] = new String[]{
                detalles.get(i).getCodigo(),
                detalles.get(i).getCantidad().toString(),
                detalles.get(i).getPrecio().toString(),
                detalles.get(i).getTotal().toString()
            };
        }
        DefaultTableModel dtm = new DefaultTableModel(data, cols);
        tblDetalles.setModel(dtm);
        tblDetalles.repaint();

        iva = subtotal * IVA;
        total = subtotal + iva;

        lblSubtotal.setText(String.format("%.2f", subtotal));
        lblIva.setText(String.format("%.2f", iva));
        lblTotal.setText(String.format("%.2f", total));
    }//GEN-LAST:event_btnCarritoActionPerformed

    private void menuItemNuevaVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNuevaVentaActionPerformed
        limpiarVenta();
    }//GEN-LAST:event_menuItemNuevaVentaActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String fecha = sdf.format(new Date());
        facturas.add(new Factura(detalles, fecha, Double.parseDouble(lblTotal.getText())));
        facturasUtils.actualizarFacturas(facturas);
        System.out.println("Nueva venta\nFecha: " + fecha
                + "\nTotal: " + lblTotal.getText()
                + "\nCódigo*********Cantidad*********Precio*********Total");
        detalles.forEach(System.out::println);
        limpiarVenta();
        JOptionPane.showMessageDialog(this, "Venta confirmada", "Venta", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void listarFacturas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarFacturas
        facturas.forEach(f -> {
            System.out.println("\nFecha: " + f.getFecha()
                    + "\nTotal: " + f.getTotal());
            System.out.println("Código*********Cantidad*********Precio*********Total");
            f.getDetalles().forEach(System.out::println);
        });
        System.out.println("Facturas listadas en la consola");
    }//GEN-LAST:event_listarFacturas

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Principal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCarrito;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblSubtotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JMenuItem menuItemActualizar;
    private javax.swing.JMenuItem menuItemAgregar;
    private javax.swing.JMenuItem menuItemEliminar;
    private javax.swing.JMenuItem menuItemIncrementar;
    private javax.swing.JMenuItem menuItemListar;
    private javax.swing.JMenuItem menuItemNuevaVenta;
    private javax.swing.JPanel panelVenta;
    private javax.swing.JTable tblDetalles;
    // End of variables declaration//GEN-END:variables
}
